# expands metadata
# generated at 2018-06-04
Gpupo\CommonSchema\ORM\Entity\People\Document:
  type: entity
  table: cs_people_document
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\People\DocumentRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    doc_type:
      type: string
      lenght: 50
      unique: false
      options: {  }
    doc_number:
      type: string
      lenght: 50
      unique: false
      options: {  }
    expands:
      type: array
      options: {  }
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
