# payment metadata
# generated at 2018-06-04
Gpupo\CommonSchema\ORM\Entity\Trading\Trading:
  type: entity
  table: cs_trading
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\TradingRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    expands:
      type: array
      options: {  }
  oneToOne:
    order:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Trading\Order\Order
      options: {  }
    payment:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Trading\Payment\Payment
      options: {  }
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
