# expands metadata
# generated at 2018-06-04
Gpupo\CommonSchema\ORM\Entity\Organization\Document:
  type: entity
  table: cs_organization_company_document
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Organization\DocumentRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    doc_type:
      type: string
      lenght: 50
      unique: false
      options: {  }
    doc_number:
      type: string
      lenght: 50
      unique: false
      options: {  }
    expands:
      type: array
      options: {  }
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
