# description metadata
# generated at 2018-06-04
Gpupo\CommonSchema\ORM\Entity\Trading\Order\OrderStatusDetail:
  type: entity
  table: cs_trading_order_status_detail
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Order\OrderStatusDetailRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    code:
      type: string
      lenght: 50
      unique: false
      options: {  }
    description:
      type: string
      lenght: 50
      unique: false
      options: {  }
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
