# expands metadata
# generated at 2018-06-04
Gpupo\CommonSchema\ORM\Entity\Trading\Order\Shippings\Transport\Item:
  type: entity
  table: cs_trading_order_shipping_transport
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Order\Shippings\Transport\ItemRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    tracking_number:
      type: string
      lenght: 50
      unique: false
      options: {  }
    tracking_link:
      type: string
      lenght: 50
      unique: false
      options: {  }
    date_ship:
      type: datetime
      options: {  }
    date_tracking_ship:
      type: datetime
      options: {  }
    delivery_service:
      type: string
      lenght: 50
      unique: false
      options: {  }
    carrier:
      type: string
      lenght: 50
      unique: false
      options: {  }
    tags:
      type: array
      options: {  }
    expands:
      type: array
      options: {  }
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
