# address_delivery metadata
# generated at 2018-06-04
Gpupo\CommonSchema\ORM\Entity\Trading\Order\Customer\Customer:
  type: entity
  table: cs_trading_order_customer
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Order\Customer\CustomerRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    nickname:
      type: string
      lenght: 50
      unique: false
      options: {  }
    email:
      type: string
      lenght: 50
      unique: false
      options: {  }
    first_name:
      type: string
      lenght: 50
      unique: false
      options: {  }
    last_name:
      type: string
      lenght: 50
      unique: false
      options: {  }
    expands:
      type: array
      options: {  }
  oneToOne:
    phone:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\People\Phone
      options: {  }
    alternative_phone:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\People\AlternativePhone
      options: {  }
    document:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\People\Document
      options: {  }
    address_billing:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Trading\Order\Customer\AddressBilling
      options: {  }
    address_delivery:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Trading\Order\Customer\AddressDelivery
      options: {  }
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
