# expands metadata
# generated at 2018-06-04
Gpupo\CommonSchema\ORM\Entity\Trading\Order\Order:
  type: entity
  table: cs_trading_order
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Order\OrderRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    order_number:
      type: string
      lenght: 50
      unique: false
      options: {  }
    order_status:
      type: string
      lenght: 50
      unique: false
      options: {  }
    order_type:
      type: string
      lenght: 50
      unique: false
      options: {  }
    date_created:
      type: datetime
      options: {  }
    date_closed:
      type: datetime
      options: {  }
    date_agreed:
      type: datetime
      options: {  }
    date_last_modified:
      type: datetime
      options: {  }
    origin_business_unit:
      type: string
      lenght: 50
      unique: false
      options: {  }
    origin_number:
      type: string
      lenght: 50
      unique: false
      options: {  }
    origin_site:
      type: string
      lenght: 50
      unique: false
      options: {  }
    currency_id:
      type: string
      lenght: 50
      unique: false
      options: {  }
    total_commission:
      type: decimal
      precision: 10
      scale: 2
      options: {  }
    total_discount:
      type: decimal
      precision: 10
      scale: 2
      options: {  }
    total_freight:
      type: decimal
      precision: 10
      scale: 2
      options: {  }
    total_gross:
      type: decimal
      precision: 10
      scale: 2
      options: {  }
    total_net:
      type: decimal
      precision: 10
      scale: 2
      options: {  }
    total_quantity:
      type: decimal
      precision: 10
      scale: 2
      options: {  }
    requested_devolution:
      type: boolean
      options: {  }
    requested_exchange:
      type: boolean
      options: {  }
    tags:
      type: array
      options: {  }
    expands:
      type: array
      options: {  }
  oneToOne:
    order_status_detail:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Trading\Order\OrderStatusDetail
      options: {  }
    customer:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Trading\Order\Customer\Customer
      options: {  }
  oneToMany:
    shipping:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Trading\Order\Shippings\Shipping
      options: {  }
      mappedBy: shipping
      joinColumn:
        name: shipping_id
        referencedColumnName: id
    payment:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Trading\Payment\Payment
      options: {  }
      mappedBy: payment
      joinColumn:
        name: payment_id
        referencedColumnName: id
    feedback:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Trading\Order\Feedback\Item
      options: {  }
      mappedBy: feedback
      joinColumn:
        name: feedback_id
        referencedColumnName: id
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
