# expands gpupo/common-schema metadata
# version: 2.0
# generated at Fri, 25 May 2018 20:35:48 +0000
Gpupo\CommonSchema\ORM\Entity\Trading\Order\Order:
  type: entity
  table: cs_trading_order
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Order\OrderRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    order_number:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    order_status:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    order_status_detail:
      type: object
      lenght: 50
      unique: false
      options:
        comment: ''
    order_type:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    date_created:
      type: datetime
      lenght: 50
      unique: false
      options:
        comment: ''
    date_closed:
      type: datetime
      lenght: 50
      unique: false
      options:
        comment: ''
    date_agreed:
      type: datetime
      lenght: 50
      unique: false
      options:
        comment: ''
    date_last_modified:
      type: datetime
      lenght: 50
      unique: false
      options:
        comment: ''
    origin_business_unit:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    origin_number:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    origin_site:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    currency_id:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    total_commission:
      type: number
      lenght: 50
      unique: false
      options:
        comment: ''
    total_discount:
      type: number
      lenght: 50
      unique: false
      options:
        comment: ''
    total_freight:
      type: number
      lenght: 50
      unique: false
      options:
        comment: ''
    total_gross:
      type: number
      lenght: 50
      unique: false
      options:
        comment: ''
    total_net:
      type: number
      lenght: 50
      unique: false
      options:
        comment: ''
    total_quantity:
      type: number
      lenght: 50
      unique: false
      options:
        comment: ''
    shippings:
      type: object
      lenght: 50
      unique: false
      options:
        comment: ''
    customer:
      type: object
      lenght: 50
      unique: false
      options:
        comment: ''
    payments:
      type: object
      lenght: 50
      unique: false
      options:
        comment: ''
    feedback:
      type: object
      lenght: 50
      unique: false
      options:
        comment: ''
    requested_devolution:
      type: boolean
      lenght: 50
      unique: false
      options:
        comment: ''
    requested_exchange:
      type: boolean
      lenght: 50
      unique: false
      options:
        comment: ''
    tags:
      type: array
      lenght: 50
      unique: false
      options:
        comment: ''
    expands:
      type: array
      lenght: 50
      unique: false
      options:
        comment: ''
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
