# expands metadata
# generated at 2018-06-04
Gpupo\CommonSchema\ORM\Entity\Trading\Order\Shippings\Seller:
  type: entity
  table: cs_trading_order_seller
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Order\Shippings\SellerRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    nickname:
      type: string
      lenght: 50
      unique: false
      options: {  }
    email:
      type: string
      lenght: 50
      unique: false
      options: {  }
    first_name:
      type: string
      lenght: 50
      unique: false
      options: {  }
    last_name:
      type: string
      lenght: 50
      unique: false
      options: {  }
    expands:
      type: array
      options: {  }
  oneToOne:
    phone:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Organization\Phone
      options: {  }
    alternative_phone:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Organization\AlternativePhone
      options: {  }
    document:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Organization\Document
      options: {  }
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
