# value metadata
# generated at 2018-06-04
Gpupo\CommonSchema\ORM\Entity\Trading\Order\Shippings\Feedback\Item:
  type: entity
  table: cs_trading_order_shipping_feedback
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Order\Shippings\Feedback\ItemRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    expands:
      type: array
      options: {  }
    key:
      type: string
      lenght: 50
      unique: false
      options: {  }
    value:
      type: string
      lenght: 50
      unique: false
      options: {  }
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
