# transaction_id metadata
# generated at 2018-06-04
Gpupo\CommonSchema\ORM\Entity\Trading\Payment\AtmTransferReference:
  type: entity
  table: cs_trading_payment_atm_transfer_reference
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Payment\AtmTransferReferenceRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    company_id:
      type: bigint
      options: {  }
    transaction_id:
      type: bigint
      options: {  }
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
