# expands metadata
# generated at 2018-06-04
Gpupo\CommonSchema\ORM\Entity\Trading\Order\Feedback\Item:
  type: entity
  table: cs_trading_order_feedback
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Order\Feedback\ItemRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    status:
      type: string
      lenght: 50
      unique: false
      options: {  }
    reason:
      type: string
      lenght: 50
      unique: false
      options: {  }
    message:
      type: string
      lenght: 50
      unique: false
      options: {  }
    rating:
      type: bigint
      options: {  }
    expands:
      type: array
      options: {  }
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
